name: build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: dedalusproject/dedalus-conda
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'v2.0-refactor'
    - name: build
      run: conda run -n dedalus pip install -e .
        
    - name: test
      run: conda run -n dedalus pytest 
        